apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
    target:
      kind: Service
      name: pipefunc-service
images:
  - name: DOCKERHUB_USERNAME/pipefunc
    newTag: latest
