name: TOC Generator

on: push

jobs:
  generateTOC:
    container:
      image: catthehacker/ubuntu:act-22.04
      options: --privileged
    name: TOC Generator
    runs-on: self-hosted
    steps:
      - uses: technote-space/toc-generator@v4
        with:
          TOC_TITLE: ""
